openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: 'https://virtserver.swaggerhub.com/ADANREHM/Hexagonal_architecture_API_example/1.0.0'
  - url: 'https://localhost:3000'
    description: Local dev server
info:
  description: Documentación de la API usada como ejemplo de desarrollo para arquitectura hexagonal
  version: 1.0.0
  title: Hexagonal architecture API example
  contact:
    name: SKRTEEEEEE
    url: 'https://profile-skrt.vercel.app'
    email: adanreh.m@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: ''
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /login:
    post:
      summary: Your POST endpoint
      tags: []
      responses:
        '200':
          description: OK
        '401':
          description: Invalid credentials
      operationId: do-login
      description: '# Do login into our app'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  x-stoplight:
                    id: 9etmagevcgxme
                password:
                  type: string
                  x-stoplight:
                    id: rk9sipjrhtss5
            examples:
              Basic User:
                value:
                  email: usuario2@prueba.com
                  password: usuarioprueba2
              Admin User:
                value:
                  email: firstAdmin@skrt.io
                  password: firstAdmin
        description: Esto es una explicación del Request body?
components:
  schemas:
    LikePost:
      type: object
      properties:
        type:
          type: string
        properties:
          type: object
          properties:
            id:
              type: object
              properties:
                type:
                  type: string
                format:
                  type: string
            userId:
              type: object
              properties:
                type:
                  type: string
                format:
                  type: string
            postId:
              type: object
              properties:
                type:
                  type: string
                format:
                  type: string
            createdAt:
              type: object
              properties:
                type:
                  type: string
                format:
                  type: string
        required:
          type: array
          items:
            type: string
      x-examples:
        Example 1:
          type: object
          properties:
            id:
              type: integer
              format: int64
            userId:
              type: integer
              format: int64
            postId:
              type: integer
              format: int64
            createdAt:
              type: string
              format: date-time
          required:
            - id
            - userId
            - postId
            - createdAt
    Post:
      type: object
      properties:
        type:
          type: string
        properties:
          type: object
          properties:
            id:
              type: object
              properties:
                type:
                  type: string
                format:
                  type: string
            title:
              type: object
              properties:
                type:
                  type: string
            content:
              type: object
              properties:
                type:
                  type: string
                nullable:
                  type: boolean
            deleted:
              type: object
              properties:
                type:
                  type: string
            authorId:
              type: object
              properties:
                type:
                  type: string
                format:
                  type: string
        required:
          type: array
          items:
            type: string
      x-examples:
        Example 1:
          type: object
          properties:
            id:
              type: integer
              format: int64
            title:
              type: string
            content:
              type: string
              nullable: true
            deleted:
              type: boolean
            authorId:
              type: integer
              format: int64
          required:
            - id
            - title
            - deleted
            - authorId
    User:
      type: object
      properties:
        type:
          type: string
        properties:
          type: object
          properties:
            id:
              type: object
              properties:
                type:
                  type: string
                format:
                  type: string
            email:
              type: object
              properties:
                type:
                  type: string
                format:
                  type: string
            password:
              type: object
              properties:
                type:
                  type: string
            name:
              type: object
              properties:
                type:
                  type: string
                nullable:
                  type: boolean
            role:
              type: object
              properties:
                type:
                  type: string
            banned:
              type: object
              properties:
                type:
                  type: string
        required:
          type: array
          items:
            type: string
      x-examples:
        Example 1:
          type: object
          properties:
            id:
              type: integer
              format: int64
            email:
              type: string
              format: email
            password:
              type: string
            name:
              type: string
              nullable: true
            role:
              type: string
            banned:
              type: boolean
          required:
            - id
            - email
            - password
            - role
            - banned
x-internal: false